#-
#              _   _  __
#  _ __   ___ | |_(_)/ _|_   _
# | '_ \ / _ \| __| | |_| | | |
# | | | | (_) | |_| |  _| |_| |
# |_| |_|\___/ \__|_|_|  \__, |
#                        |___/
#
#- from github.com/basnijholt/home-assistant-config


      


- platform: group
  name: all_devices_leon_+_iphone_ellen
  services:
      - service: pushoverleon
      - service: mobile_app_iphone_12_pro_van_leon
      - service: mobile_app_ipad_pro_129_van_leon
      - service: mobile_app_macbook_pro
      - service: mobile_app_iphone_van_ellen      
      

      
      
      

