# Theme based on Dwains Dashboard
# Creator: LRvdLinden
# Website: https://github.com/LRvdLinden
# v.2.0.2
#
Dwains Light Theme:
  #Fonts
  primary-font-family: 'Open Sans'
  paper-font-common-base_-_font-family: 'var(--primary-font-family)'
  paper-font-common-code_-_font-family: 'var(--primary-font-family)'
  paper-font-body1_-_font-family: 'var(--primary-font-family)'
  paper-font-subhead_-_font-family: 'var(--primary-font-family)'
  paper-font-headline_-_font-family: 'var(--primary-font-family)'
  paper-font-caption_-_font-family: 'var(--primary-font-family)'
  paper-font-title_-_font-family: 'var(--primary-font-family)'
  ha-card-header-font-family: 'var(--primary-font-family)'
  # Header:
  app-header-background-color: '#262628'
  app-header-text-color: '#f2f2f7'
  paper-tabs-selection-bar-color: '#262628'
  # Main Interface Colors
  primary-color: rgb(41, 158, 194)
  light-primary-color: var(--primary-color)
  primary-background-color: '#f2f2f7'
  secondary-background-color: '#f2f2f7'
  divider-color: var(--primary-background-color)
  accent-color: rgb(41, 158, 194)
  # Text
  primary-text-color: '#262628'
  secondary-text-color: rgb(95, 99, 104)
  text-primary-color: rgb(255, 255, 255)
  disabled-text-color: var(--primary-background-color)
  # Sidebar Menu
  sidebar-icon-color: rgb(41, 158, 194)
  sidebar-text-color: var(--primary-text-color)
  sidebar-background-color: '#f2f2f7'
  sidebar-selected-background-color: '#f2f2f7'
  sidebar-selected-icon-color: rgb(41, 158, 194)
  sidebar-selected-text-color: rgb(41, 158, 194)
  # Buttons
  paper-item-icon-color: rgb(41, 158, 194)
  paper-item-icon-active-color: rgb(41, 158, 194)
  # States and Badges
  state-icon-color: rgb(41, 158, 194)
  state-icon-active-color: rgb(255, 214, 10)
  state-icon-unavailable-color: rgb(169, 177, 188)
  # Sliders
  paper-slider-knob-color: rgb(41, 158, 194)
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  # Labels
  label-badge-background-color: rgb(248, 250, 249)
  label-badge-text-color: rgb(77, 85, 117)
  label-badge-red: rgb(199, 72, 76)
  label-badge-green: rgb(109, 192, 113)
  label-badge-blue: rgb(41, 158, 194)
  label-badge-yellow: rgb(217, 183, 87)
  label-badge-gray: rgb(95, 98, 103)
  # Cards
  card-background-color: rgb(255, 255, 255)
  ha-card-border-radius: "10px"
  ha-card-box-shadow: none
  paper-dialog-background-color: var(--card-background-color)
  paper-listbox-background-color: var(--card-background-color)
  paper-card-background-color: var(--card-background-color)
  # Switches
  switch-checked-button-color: '#f2f2f7'              
  switch-unchecked-button-color: '#616161'               
  switch-checked-track-color: rgb(41, 158, 194)                
  switch-unchecked-track-color: '#131314'   
  # Toggles
  paper-toggle-button-checked-button-color: var(--switch-checked-button-color)
  paper-toggle-button-checked-bar-color: var(--switch-checked-track-color)
  paper-toggle-button-unchecked-button-color: var(--switch-unchecked-button-color)
  paper-toggle-button-unchecked-bar-color: var(--switch-unchecked-track-color)
  # Table
  table-row-background-color: var(--card-background-color)
  table-row-alternative-background-color: var(--primary-background-color)
  data-table-background-color: var(--primary-background-color)
  # Dropdowns
  material-background-color: var(--card-background-color)
  material-secondary-background-color: var(--primary-background-color)
  mdc-theme-surface: var(--paper-card-background-color)
  # Pre/Code
  markdown-code-background-color: rgb(242, 242, 242)
  
  #DWAINS DASHBOARD
  dwains-theme-background: '#f2f2f7'
  dwains-theme-primary: '#FFFFFF'
  dwains-theme-accent: 'placeholder_primary_color'
  dwains-theme-names: '#101012'
  dwains-theme-grey: '#adadb7'
  dwains-theme-header-background: '#262628'
  dwains-theme-header-text: '#f2f2f7'
  dwains-theme-header-button-text: '#f2f2f7'
  dwains-theme-header-button-background: '#1c1c1e'
  dwains-theme-unavailable: '#303030'
  dwains-theme-off: '#909090' 
