  - platform: afvalbeheer
    wastecollector: circulus-berkel
    resources:                       
      - gft
      - papier
      - pmd
    postcode: !secret postcode     
    streetnumber: !secret streetnumber                
    upcomingsensor: 1               
    dateformat: '%d-%m-%Y'          
    dateonly: 0                     
    dateobject: 0                  
    name: ''                         
    nameprefix: 1                   
    builtinicons: 1                 
    disableicons: 0                 
    dutch: 1  