- platform: buienradar
  name: "Apeldoorn"
 # Force 'Meetstation Volkel' to be used:
  latitude: 11.11
  longitude: 1.11
  monitored_conditions:
    - stationname
    - barometerfc
    - barometerfcname
    - conditioncode
    - condition
    - conditiondetailed
    - conditionexact
    - symbol
    - feeltemperature
    - humidity
    - temperature
    - groundtemperature
    - windspeed
    - windforce
    - winddirection
    - windazimuth
    - pressure
    - visibility
    - windgust
    - precipitation
    - irradiance
    - precipitation_forecast_average
    - precipitation_forecast_total
    - rainlast24hour
    - rainlasthour
      # conditions for forecasted data:
    - symbol_1d
    - symbol_2d
    - symbol_3d
    - symbol_4d
    - symbol_5d
    - temperature_1d
    - temperature_2d
    - temperature_3d
    - temperature_4d
    - temperature_5d
    - mintemp_1d
    - rainchance_1d
    - rainchance_2d
    - sunchance_1d
    - sunchance_2d
    - rain_1d
    - rain_2d
    - minrain_1d
    - maxrain_1d
    - windforce_1d
    - windforce_2d
    - windspeed_1d
    - windspeed_2d
    - winddirection_1d
    - winddirection_2d
    - windazimuth_1d
    - windazimuth_2d
