#
# Energy calculation
#
# https://community.home-assistant.io/t/custom-component-homewizard-energy-wifi-p1-meter/227441/52?fbclid=IwAR0r8MLFPQFGkwnGJ6WaeevDVE5a7orRuUr_-RwlLbQzgnN_Rr3pNRhzmLE
#

# import gas
- platform: template
  sensors:
    energy_gass_eur:
      friendly_name: 'Kosten vandaag gas'
      value_template: "{{ (states('sensor.gas_daily')|float * states('input_number.gas_energy_cost')|float)|round(2) }}"
      unit_of_measurement: "€"
      icon_template: mdi:currency-eur

# PRICES GAS
- platform: template
  sensors:
    gas_price_today:
      unit_of_measurement: 'EUR'
      value_template: >-
        {% set a = states('sensor.gas_daily') | float %}
        {% set b = states('input_number.all_in_enkeltarief_gas') | float %}
        {% set c = states('input_number.netbeheerkosten_gas') | float %}
        {% set d = states('input_number.vaste_leveringskosten_gas') | float %}
        {{ (((a * b) + c) + d) | round(2) }}
    gas_price_yesterday:
      unit_of_measurement: 'EUR'
      value_template: >-
        {% set a = states('sensor.gas_yesterday') | float %}
        {% set b = states('input_number.all_in_enkeltarief_gas') | float %}
        {% set c = states('input_number.netbeheerkosten_gas') | float %}
        {% set d = states('input_number.vaste_leveringskosten_gas') | float %}
        {{ (((a * b) + c) + d) | round(2) }}
    gas_price_week:
      unit_of_measurement: 'EUR'
      value_template: >-
        {% set a = states('sensor.gas_weekly') | float %}
        {% set b = states('input_number.all_in_enkeltarief_gas') | float %}
        {% set c = states('input_number.netbeheerkosten_gas') | float %}
        {% set d = states('input_number.vaste_leveringskosten_gas') | float %}
        {{ (((a * b) + ((c * 365) / 52)) + ((d * 365) / 52)) | round(2) }}
    gas_price_last_week:
      unit_of_measurement: 'EUR'
      value_template: >-
        {% set a = states('sensor.gas_last_week') | float %}
        {% set b = states('input_number.all_in_enkeltarief_gas') | float %}
        {% set c = states('input_number.netbeheerkosten_gas') | float %}
        {% set d = states('input_number.vaste_leveringskosten_gas') | float %}
        {{ (((a * b) + ((c * 365) / 52)) + ((d * 365) / 52)) | round(2) }}
    gas_price_month:
      unit_of_measurement: 'EUR'
      value_template: >-
        {% set a = states('sensor.gas_monthly') | float %}
        {% set b = states('input_number.all_in_enkeltarief_gas') | float %}
        {% set c = states('input_number.netbeheerkosten_gas') | float %}
        {% set d = states('input_number.vaste_leveringskosten_gas') | float %}
        {{ (((a * b) + ((c * 365) / 12)) + ((d * 365) / 12)) | round(2) }}
    gas_price_last_month:
      unit_of_measurement: 'EUR'
      value_template: >-
        {% set a = states('sensor.gas_last_month') | float %}
        {% set b = states('input_number.all_in_enkeltarief_gas') | float %}
        {% set c = states('input_number.netbeheerkosten_gas') | float %}
        {% set d = states('input_number.vaste_leveringskosten_gas') | float %}
        {{ (((a * b) + ((c * 365) / 12)) + ((d * 365) / 12)) | round(2) }}
    gas_price_year:
      unit_of_measurement: 'EUR'
      value_template: >-
        {% set a = states('sensor.gas_yearly') | float %}
        {% set b = states('input_number.all_in_enkeltarief_gas') | float %}
        {% set c = states('input_number.netbeheerkosten_gas') | float %}
        {% set d = states('input_number.vaste_leveringskosten_gas') | float %}
        {{ (((a * b) + (c * 365)) + (d * 365)) | round(2) }}
    gas_price_last_year:
      unit_of_measurement: 'EUR'
      value_template: >-
        {% set a = states('sensor.gas_last_year') | float %}
        {% set b = states('input_number.all_in_enkeltarief_gas') | float %}
        {% set c = states('input_number.netbeheerkosten_gas') | float %}
        {% set d = states('input_number.vaste_leveringskosten_gas') | float %}
        {{ (((a * b) + (c * 365)) + (d * 365)) | round(2) }}

# LAST PERIODS gas
- platform: template
  sensors:
    gas_yesterday:
      friendly_name: Yesterday Gas
      unit_of_measurement: m3
      value_template: "{{ state_attr('sensor.gas_daily','last_period') }}"
    gas_last_week:
      friendly_name: last Week Gas
      unit_of_measurement: m3
      value_template: "{{ state_attr('sensor.gas_weekly','last_period') }}"
    gas_last_month:
      friendly_name: last Month Gas
      unit_of_measurement: m3
      value_template: "{{ state_attr('sensor.gas_monthly','last_period') }}"
    gas_last_year:
      friendly_name: last Year Gas
      unit_of_measurement: m3
      value_template: "{{ state_attr('sensor.gas_yearly','last_period') }}"

#Gemiddeld
    average_gas_day:
      unit_of_measurement: 'm3'
      value_template: >-
        {% set a = states('sensor.gas_last_month') | float %}
        {{ (a / 30.41) | round(3) }}