#-
#  _                          _    _ _
# | |__   ___  _ __ ___   ___| | _(_) |_
# | '_ \ / _ \| '_ ` _ \ / _ \ |/ / | __|
# | | | | (_) | | | | | |  __/   <| | |_
# |_| |_|\___/|_| |_| |_|\___|_|\_\_|\__|
#
#
#- from github.com/basnijholt/home-assistant-config
  auto_start: true