---
#-
#  _                   _                             _
# (_)_ __  _ __  _   _| |_     _ __  _   _ _ __ ___ | |__   ___ _ __ ___
# | | '_ \| '_ \| | | | __|   | '_ \| | | | '_ ` _ \| '_ \ / _ \ '__/ __|
# | | | | | |_) | |_| | |_    | | | | |_| | | | | | | |_) |  __/ |  \__ \
# |_|_| |_| .__/ \__,_|\__|___|_| |_|\__,_|_| |_| |_|_.__/ \___|_|  |___/
#         |_|            |_____|
#
#- from github.com/basnijholt/home-assistant-config

temperature_low:
  name: Temperature low
  min: 10
  max: 20
  initial: 14
  step: 0.5
  icon: mdi:temperature-celsius

temperature_high:
  name: Temperature high
  min: 10
  max: 20
  initial: 20
  step: 0.5
  icon: mdi:temperature-celsius

radio_volume:
  name: Volume
  icon: mdi:volume-high
  initial: 0.3
  min: 0
  max: 1
  step: 0.05
  mode: box