
#-
#  _                   _          _       _       _   _
# (_)_ __  _ __  _   _| |_     __| | __ _| |_ ___| |_(_)_ __ ___   ___  ___
# | | '_ \| '_ \| | | | __|   / _` |/ _` | __/ _ \ __| | '_ ` _ \ / _ \/ __|
# | | | | | |_) | |_| | |_   | (_| | (_| | ||  __/ |_| | | | | | |  __/\__ \
# |_|_| |_| .__/ \__,_|\__|___\__,_|\__,_|\__\___|\__|_|_| |_| |_|\___||___/
#         |_|            |_____|
#
#- from github.com/basnijholt/home-assistant-config
alarm_clock:
  name: Alarm clock
  has_date: false
  has_time: true

washing_machine_on:
  name: Washing machine last started
  has_date: true
  has_time: true

washing_machine_off:
  name: Washing machine last done
  has_date: true
  has_time: true

both_date_and_time:
  name: Input with both date and time
  has_date: true
  has_time: true
  
only_date:
  name: Input with only date
  has_date: true
  has_time: false
  
only_time:
  name: Input with only time
  has_date: false
  has_time: true