#-
#                  _   _  __
#  ___ _ __   ___ | |_(_)/ _|_   _
# / __| '_ \ / _ \| __| | |_| | | |
# \__ \ |_) | (_) | |_| |  _| |_| |
# |___/ .__/ \___/ \__|_|_|  \__, |
#     |_|                    |___/
#
#- from github.com/basnijholt/home-assistant-config

  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret