#-
#               _               _
# __      _____| |__   ___  ___| |___   __
# \ \ /\ / / _ \ '_ \ / _ \/ __| __\ \ / /
#  \ V  V /  __/ |_) | (_) \__ \ |_ \ V /
#   \_/\_/ \___|_.__/ \___/|___/\__| \_/
#
#
#- from github.com/basnijholt/home-assistant-config
  - name: TV Woonkamer
    host: !secret
  - name: TV Kai
    host: !secret
