#-
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|  |___/
#                           |___/_____|
#
#- from github.com/basnijholt/home-assistant-config
 
  - platform: command_line
    name: "Nas van Leon"
    command: response=$(curl -LIk -m 3 http://192.168.1.131 -o /dev/null -w "%{http_code}\n" -s); test "$response" -ge 200 && echo "Online" || echo "Offline"
    scan_interval: 90
    value_template: "{{ value }}"
