#-
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|  |___/
#                           |___/_____|
#
#- from github.com/basnijholt/home-assistant-config
    
  - platform: workday
    name: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - '2021-04-26' #Roostervrije dag
      - '2021-04-27' #Koningsdag
      - '2021-05-03' #Mei vakantie
      - '2021-05-04' #Mei vakantie
      - '2021-05-05' #Bevrijdingsdag
      - '2021-05-06' #Mei vakantie
      - '2021-05-07' #Mei vakantie
      - '2021-05-13' #Hemelvaartsdag
      - '2021-05-14' #Roostervrije dag
      - '2021-05-24' #2e Pinksterdag
      - '2021-05-25' #Roostervrije dag
      - '2021-05-26' #Roostervrije dag
      - '2021-07-19' #Zomervakantie
      - '2021-07-20' #Zomervakantie
      - '2021-07-21' #Zomervakantie
      - '2021-07-22' #Zomervakantie
      - '2021-07-23' #Zomervakantie
      - '2021-07-19' #Zomervakantie
      - '2021-07-26' #Zomervakantie
      - '2021-07-27' #Zomervakantie
      - '2021-07-28' #Zomervakantie
      - '2021-07-29' #Zomervakantie
      - '2021-07-30' #Zomervakantie
      - '2021-08-02' #Zomervakantie
      - '2021-08-03' #Zomervakantie
      - '2021-08-04' #Zomervakantie 
      - '2021-08-05' #Zomervakantie 
      - '2021-08-06' #Zomervakantie 
      - '2021-08-09' #Zomervakantie 
      - '2021-08-10' #Zomervakantie 
      - '2021-08-11' #Zomervakantie 
      - '2021-08-12' #Zomervakantie 
      - '2021-08-13' #Zomervakantie 
      - '2021-08-16' #Zomervakantie 
      - '2021-08-17' #Zomervakantie 
      - '2021-08-18' #Zomervakantie 
      - '2021-08-19' #Zomervakantie 
      - '2021-08-20' #Zomervakantie 
      - '2021-08-23' #Zomervakantie 
      - '2021-08-24' #Zomervakantie 
      - '2021-08-25' #Zomervakantie 
      - '2021-08-26' #Zomervakantie 
      - '2021-08-27' #Zomervakantie 
      - '2021-08-30' #Zomervakantie 
      - '2021-08-31' #Zomervakantie 
      - '2021-09-01' #Zomervakantie 
      - '2021-09-02' #Zomervakantie 
      - '2021-09-03' #Zomervakantie 
      
 