#-
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|  |___/
#                           |___/_____|
#
#- from github.com/basnijholt/home-assistant-config
 

  - platform: template
    sensors:    
      worked_enough_today:
        friendly_name: Worked enough today
        value_template: >
          {{ states("sensor.time_at_work_today") | float(0) > 8 }}
        icon_template: mdi:work
 